+ {'added'}
+   YamlNode(tag='!added', value='')
  {'changed_tag'}
#   <YamlNode>
-   !changed_tag
-     'changed_tag_value'
+   !Changed_tag
+     'changed_tag_value'
  {'changed_value'}
#   <YamlNode>
    !changed_value
-     'old_value'
+     'new_value'
  {'recursive_mapping'}
#   <YamlNode>
    !mapping
      {'child'}
#       <YamlNode>
        !mapping
          {'var'}
-           'bar'
+           'baz'
      {'var'}
        'foo'
- {'removed'}
-   YamlNode(tag='!removed', value='')
  {'sequence'}
#   <YamlNode>
    !sequence
      [0]
        'foo'
+     [1]
+       'baz'
      [2]
        'bar'
-     [3]
-       'baz'
  {'unchanged_value'}
#   <YamlNode>
    !unchanged_value
      'unchanged_value'
