"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/a_vs_a.json
"""
import nested_diff


def test_diff():
    a = 'a'
    b = 'a'
    diff = {'U': 'a'}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'U': 'a'}
    target = 'a'
    patched = 'a'
    assert patched == nested_diff.patch(target, diff)
