"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/nested_lists_noU.json
"""
import nested_diff


def test_diff():
    a = [0, [[100]], [20, '30'], 4]
    b = [0, [[100]], [20, '31'], 5]
    diff = {'D': [{'I': 2, 'D': [{'O': '30', 'I': 1, 'N': '31'}]}, {'O': 4, 'N': 5}]}
    opts = {'U': False}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'D': [{'I': 2, 'D': [{'O': '30', 'I': 1, 'N': '31'}]}, {'O': 4, 'N': 5}]}
    target = [0, [[100]], [20, '30'], 4]
    patched = [0, [[100]], [20, '31'], 5]
    assert patched == nested_diff.patch(target, diff)
