"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/a_vs_b.json
"""
import nested_diff


def test_diff():
    a = 'a'
    b = 'b'
    diff = {'O': 'a', 'N': 'b'}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'O': 'a', 'N': 'b'}
    target = 'a'
    patched = 'b'
    assert patched == nested_diff.patch(target, diff)
