"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/lists_with_one_different_item.json
"""
import nested_diff


def test_diff():
    a = [0]
    b = [1]
    diff = {'D': [{'O': 0, 'N': 1}]}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'D': [{'O': 0, 'N': 1}]}
    target = [0]
    patched = [1]
    assert patched == nested_diff.patch(target, diff)
