"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/nested_mixed_structures_noOU.json
"""
import nested_diff


def test_diff():
    a = {'one': [{'two': {'three': [7, 4]}}, 8]}
    b = {'one': [{'two': {'three': [7, 3]}}, 8]}
    diff = {'D': {'one': {'D': [{'D': {'two': {'D': {'three': {'D': [{'I': 1, 'N': 3}]}}}}}]}}}
    opts = {'O': False, 'U': False}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    a = {'one': [{'two': {'three': [7, 4]}}, 8]}
    b = {'one': [{'two': {'three': [7, 3]}}, 8]}
    diff = {'D': {'one': {'D': [{'D': {'two': {'D': {'three': {'D': [{'I': 1, 'N': 3}]}}}}}]}}}
    assert b == nested_diff.patch(a, diff)
