"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/one_item_inserted_in_the_middle_of_list.json
"""
import nested_diff


def test_diff():
    a = [0, 2]
    b = [0, 1, 2]
    diff = {'D': [{'U': 0}, {'A': 1}, {'U': 2}]}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'D': [{'U': 0}, {'A': 1}, {'U': 2}]}
    target = [0, 2]
    patched = [0, 1, 2]
    assert patched == nested_diff.patch(target, diff)
