"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/deeply_nested_sublist_removed_from_list.json
"""
import nested_diff


def test_diff():
    a = [0, [[0, 1]]]
    b = [0]
    diff = {'D': [{'U': 0}, {'R': [[0, 1]]}]}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'D': [{'U': 0}, {'R': [[0, 1]]}]}
    target = [0, [[0, 1]]]
    patched = [0]
    assert patched == nested_diff.patch(target, diff)
