"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/subhash_emptied_noR.json
"""
import nested_diff


def test_diff():
    a = {'one': {'two': 2}}
    b = {'one': {}}
    diff = {}
    opts = {'R': False}
    assert diff == nested_diff.diff(a, b, **opts)
