"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/list_with_one_item_vs_empty_list.json
"""
import nested_diff


def test_diff():
    a = [0]
    b = []
    diff = {'D': [{'R': 0}]}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    a = [0]
    b = []
    diff = {'D': [{'R': 0}]}
    assert b == nested_diff.patch(a, diff)
