"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/hashes_with_one_different_value_noO.json
"""
import nested_diff


def test_diff():
    a = {'one': 1}
    b = {'one': 2}
    diff = {'D': {'one': {'N': 2}}}
    opts = {'O': False}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'D': {'one': {'N': 2}}}
    target = {'one': 1}
    patched = {'one': 2}
    assert patched == nested_diff.patch(target, diff)
