"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/undef_vs_negative_number.json
"""
import nested_diff


def test_diff():
    a = None
    b = -1
    diff = {'N': -1, 'O': None}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    a = None
    b = -1
    diff = {'N': -1, 'O': None}
    assert b == nested_diff.patch(a, diff)
