"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/0_vs_1.json
"""
import nested_diff


def test_diff():
    a = 0
    b = 1
    diff = {'O': 0, 'N': 1}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'O': 0, 'N': 1}
    target = 0
    patched = 1
    assert patched == nested_diff.patch(target, diff)
