"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/0_vs_0.json
"""
import nested_diff


def test_diff():
    a = 0
    b = 0
    diff = {'U': 0}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'U': 0}
    target = 0
    patched = 0
    assert patched == nested_diff.patch(target, diff)
