"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/a_vs_b.json
"""

from __future__ import unicode_literals

import nested_diff


def test_diff():
    a = 'a'
    b = 'b'
    diff = {'N': 'b', 'O': 'a'}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    a = 'a'
    b = 'b'
    diff = {'N': 'b', 'O': 'a'}
    assert b == nested_diff.patch(a, diff)
