"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/lists_LCS_complex_noU.json
"""
import nested_diff


def test_diff():
    a = ['a', 'b', 'c', 'e', 'h', 'j', 'l', 'm', 'n', 'p']
    b = ['b', 'c', 'd', 'e', 'f', 'j', 'k', 'l', 'm', 'r', 's', 't']
    diff = {'D': [{'R': 'a'}, {'A': 'd', 'I': 3}, {'O': 'h', 'I': 4, 'N': 'f'}, {'A': 'k', 'I': 6}, {'O': 'n', 'I': 8, 'N': 'r'}, {'O': 'p', 'N': 's'}, {'A': 't'}]}
    opts = {'U': False}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'D': [{'R': 'a'}, {'A': 'd', 'I': 3}, {'O': 'h', 'I': 4, 'N': 'f'}, {'A': 'k', 'I': 6}, {'O': 'n', 'I': 8, 'N': 'r'}, {'O': 'p', 'N': 's'}, {'A': 't'}]}
    target = ['a', 'b', 'c', 'e', 'h', 'j', 'l', 'm', 'n', 'p']
    patched = ['b', 'c', 'd', 'e', 'f', 'j', 'k', 'l', 'm', 'r', 's', 't']
    assert patched == nested_diff.patch(target, diff)
