"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/empty_string_vs_undef.json
"""
import nested_diff


def test_diff():
    a = ''
    b = None
    diff = {'N': None, 'O': ''}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    a = ''
    b = None
    diff = {'N': None, 'O': ''}
    assert b == nested_diff.patch(a, diff)
