"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/nested_hashes_with_one_equal_value_noU.json
"""
import nested_diff


def test_diff():
    a = {'one': {'two': {'three': 3}}}
    b = {'one': {'two': {'three': 3}}}
    diff = {}
    opts = {'U': False}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    a = {'one': {'two': {'three': 3}}}
    b = {'one': {'two': {'three': 3}}}
    diff = {}
    assert b == nested_diff.patch(a, diff)
