"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/undef_vs_empty_hash_noOU.json
"""

from __future__ import unicode_literals

import nested_diff


def test_diff():
    a = None
    b = {}
    diff = {}
    opts = {'N': False, 'O': False}
    assert diff == nested_diff.diff(a, b, **opts)
