"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/nested_hashes_with_one_different_value.json
"""
import nested_diff


def test_diff():
    a = {'one': {'two': {'three': 3}}}
    b = {'one': {'two': {'three': 4}}}
    diff = {'D': {'one': {'D': {'two': {'D': {'three': {'N': 4, 'O': 3}}}}}}}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    a = {'one': {'two': {'three': 3}}}
    b = {'one': {'two': {'three': 4}}}
    diff = {'D': {'one': {'D': {'two': {'D': {'three': {'N': 4, 'O': 3}}}}}}}
    assert b == nested_diff.patch(a, diff)
