"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/subhash_filled.json
"""
import nested_diff


def test_diff():
    a = {'one': {}}
    b = {'one': {'two': 2}}
    diff = {'D': {'one': {'D': {'two': {'A': 2}}}}}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'D': {'one': {'D': {'two': {'A': 2}}}}}
    target = {'one': {}}
    patched = {'one': {'two': 2}}
    assert patched == nested_diff.patch(target, diff)
