"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/1.0_vs_1.0_as_string.json
"""
import nested_diff


def test_diff():
    a = 1
    b = '1.0'
    diff = {'O': 1, 'N': '1.0'}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'O': 1, 'N': '1.0'}
    target = 1
    patched = '1.0'
    assert patched == nested_diff.patch(target, diff)
