"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/1_vs_1.0.json
"""
import nested_diff


def test_diff():
    a = 1
    b = 1
    diff = {'U': 1}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'U': 1}
    target = 1
    patched = 1
    assert patched == nested_diff.patch(target, diff)
