"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/one_key_added_to_subhash_noU.json
"""
import nested_diff


def test_diff():
    a = {'one': {'two': 2}}
    b = {'one': {'three': 3, 'two': 2}}
    diff = {'D': {'one': {'D': {'three': {'A': 3}}}}}
    opts = {'U': False}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    a = {'one': {'two': 2}}
    b = {'one': {'three': 3, 'two': 2}}
    diff = {'D': {'one': {'D': {'three': {'A': 3}}}}}
    assert b == nested_diff.patch(a, diff)
