"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/empty_hash_vs_hash_with_one_key.json
"""

from __future__ import unicode_literals

import nested_diff


def test_diff():
    a = {}
    b = {'one': 1}
    diff = {'D': {'one': {'A': 1}}}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    a = {}
    b = {'one': 1}
    diff = {'D': {'one': {'A': 1}}}
    assert b == nested_diff.patch(a, diff)
