"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/nested_hashes_noU.json
"""
import nested_diff


def test_diff():
    a = {'three': 3, 'one': 1, 'two': {'ten': 10, 'nine': 9}}
    b = {'four': 4, 'one': 1, 'two': {'ten': 10, 'nine': 8}}
    diff = {'D': {'four': {'A': 4}, 'three': {'R': 3}, 'two': {'D': {'nine': {'O': 9, 'N': 8}}}}}
    opts = {'U': False}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'D': {'four': {'A': 4}, 'three': {'R': 3}, 'two': {'D': {'nine': {'O': 9, 'N': 8}}}}}
    target = {'three': 3, 'one': 1, 'two': {'ten': 10, 'nine': 9}}
    patched = {'four': 4, 'one': 1, 'two': {'ten': 10, 'nine': 8}}
    assert patched == nested_diff.patch(target, diff)
