"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/nested_hashes_with_one_different_value.json
"""
import nested_diff


def test_diff():
    a = {'one': {'two': {'three': 3}}}
    b = {'one': {'two': {'three': 4}}}
    diff = {'D': {'one': {'D': {'two': {'D': {'three': {'O': 3, 'N': 4}}}}}}}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'D': {'one': {'D': {'two': {'D': {'three': {'O': 3, 'N': 4}}}}}}}
    target = {'one': {'two': {'three': 3}}}
    patched = {'one': {'two': {'three': 4}}}
    assert patched == nested_diff.patch(target, diff)
