"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/0_vs_undef.json
"""
import nested_diff


def test_diff():
    a = 0
    b = None
    diff = {'O': 0, 'N': None}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'O': 0, 'N': None}
    target = 0
    patched = None
    assert patched == nested_diff.patch(target, diff)
