"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/lists_LCS_changed_items_noOU.json
"""
import nested_diff


def test_diff():
    a = [0, 1, 2, 3, 4, 5, 6, 7]
    b = [0, 1, 9, 9, 4, 9, 6, 7]
    diff = {'D': [{'I': 2, 'N': 9}, {'N': 9}, {'I': 5, 'N': 9}]}
    opts = {'O': False, 'U': False}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    a = [0, 1, 2, 3, 4, 5, 6, 7]
    b = [0, 1, 9, 9, 4, 9, 6, 7]
    diff = {'D': [{'I': 2, 'N': 9}, {'N': 9}, {'I': 5, 'N': 9}]}
    assert b == nested_diff.patch(a, diff)
