"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/deeply_nested_hash_vs_empty_hash_trimR.json
"""
import nested_diff


def test_diff():
    a = {'one': {'two': {'three': 3}}}
    b = {}
    diff = {'D': {'one': {'R': None}}}
    opts = {'trimR': True}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    a = {'one': {'two': {'three': 3}}}
    b = {}
    diff = {'D': {'one': {'R': None}}}
    assert b == nested_diff.patch(a, diff)
