"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/one_item_unshifted_to_list_noU.json
"""
import nested_diff


def test_diff():
    a = [1]
    b = [0, 1]
    diff = {'D': [{'A': 0}]}
    opts = {'U': False}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'D': [{'A': 0}]}
    target = [1]
    patched = [0, 1]
    assert patched == nested_diff.patch(target, diff)
