"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/undef_vs_empty_hash_noNO.json
"""
import nested_diff


def test_diff():
    a = None
    b = {}
    diff = {}
    opts = {'O': False, 'N': False}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {}
    target = None
    patched = None
    assert patched == nested_diff.patch(target, diff)
