"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/subhash_filled_noA.json
"""
import nested_diff


def test_diff():
    a = {'one': {}}
    b = {'one': {'two': 2}}
    diff = {}
    opts = {'A': False}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {}
    target = {'one': {}}
    patched = {'one': {}}
    assert patched == nested_diff.patch(target, diff)
