"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/sublist_emptied.json
"""
import nested_diff


def test_diff():
    a = [[0]]
    b = [[]]
    diff = {'D': [{'D': [{'R': 0}]}]}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'D': [{'D': [{'R': 0}]}]}
    target = [[0]]
    patched = [[]]
    assert patched == nested_diff.patch(target, diff)
