"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/undef_vs_0.json
"""
import nested_diff


def test_diff():
    a = None
    b = 0
    diff = {'O': None, 'N': 0}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'O': None, 'N': 0}
    target = None
    patched = 0
    assert patched == nested_diff.patch(target, diff)
