"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/1.0_vs_1.0_as_string.json
"""

from __future__ import unicode_literals

import nested_diff


def test_diff():
    a = 1
    b = '1.0'
    diff = {'N': '1.0', 'O': 1}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    a = 1
    b = '1.0'
    diff = {'N': '1.0', 'O': 1}
    assert b == nested_diff.patch(a, diff)
