"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/nested_hashes_noU.json
"""
import nested_diff


def test_diff():
    a = {'three': 3, 'two': {'nine': 9, 'ten': 10}, 'one': 1}
    b = {'four': 4, 'two': {'nine': 8, 'ten': 10}, 'one': 1}
    diff = {'D': {'three': {'R': 3}, 'four': {'A': 4}, 'two': {'D': {'nine': {'N': 8, 'O': 9}}}}}
    opts = {'U': False}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    a = {'three': 3, 'two': {'nine': 9, 'ten': 10}, 'one': 1}
    b = {'four': 4, 'two': {'nine': 8, 'ten': 10}, 'one': 1}
    diff = {'D': {'three': {'R': 3}, 'four': {'A': 4}, 'two': {'D': {'nine': {'N': 8, 'O': 9}}}}}
    assert b == nested_diff.patch(a, diff)
