"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/nested_mixed_structures.json
"""
import nested_diff


def test_diff():
    a = {'one': [{'two': {'three': [7, 4]}}, 8]}
    b = {'one': [{'two': {'three': [7, 3]}}, 8]}
    diff = {'D': {'one': {'D': [{'D': {'two': {'D': {'three': {'D': [{'U': 7}, {'O': 4, 'N': 3}]}}}}}, {'U': 8}]}}}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'D': {'one': {'D': [{'D': {'two': {'D': {'three': {'D': [{'U': 7}, {'O': 4, 'N': 3}]}}}}}, {'U': 8}]}}}
    target = {'one': [{'two': {'three': [7, 4]}}, 8]}
    patched = {'one': [{'two': {'three': [7, 3]}}, 8]}
    assert patched == nested_diff.patch(target, diff)
