"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/one_item_shifted_from_list.json
"""
import nested_diff


def test_diff():
    a = [0, 1]
    b = [1]
    diff = {'D': [{'R': 0}, {'U': 1}]}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'D': [{'R': 0}, {'U': 1}]}
    target = [0, 1]
    patched = [1]
    assert patched == nested_diff.patch(target, diff)
