"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/nested_lists_LCS_noU.json
"""

from __future__ import unicode_literals

import nested_diff


def test_diff():
    a = ['a', 'b', 'c', 'e', 'h', 'j', 'l', 'm', 'n', 'p']
    b = ['b', 'c', 'd', 'e', 'f', 'j', 'k', 'l', 'm', 'r', 's', 't']
    diff = {'D': [{'R': 'a'}, {'A': 'd', 'I': 3}, {'N': 'f', 'O': 'h', 'I': 4}, {'A': 'k', 'I': 6}, {'N': 'r', 'O': 'n', 'I': 8}, {'N': 's', 'O': 'p'}, {'A': 't'}]}
    opts = {'U': False}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    a = ['a', 'b', 'c', 'e', 'h', 'j', 'l', 'm', 'n', 'p']
    b = ['b', 'c', 'd', 'e', 'f', 'j', 'k', 'l', 'm', 'r', 's', 't']
    diff = {'D': [{'R': 'a'}, {'A': 'd', 'I': 3}, {'N': 'f', 'O': 'h', 'I': 4}, {'A': 'k', 'I': 6}, {'N': 'r', 'O': 'n', 'I': 8}, {'N': 's', 'O': 'p'}, {'A': 't'}]}
    assert b == nested_diff.patch(a, diff)
