"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/nested_lists_noU.json
"""
import nested_diff


def test_diff():
    a = [0, [[100]], [20, '30'], 4]
    b = [0, [[100]], [20, '31'], 5]
    diff = {'D': [{'I': 2, 'D': [{'I': 1, 'O': '30', 'N': '31'}]}, {'N': 5, 'O': 4}]}
    opts = {'U': False}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    a = [0, [[100]], [20, '30'], 4]
    b = [0, [[100]], [20, '31'], 5]
    diff = {'D': [{'I': 2, 'D': [{'I': 1, 'O': '30', 'N': '31'}]}, {'N': 5, 'O': 4}]}
    assert b == nested_diff.patch(a, diff)
