"""
Do not edit manually! Generated by tests/gen_ext_tests.py from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/nested_hashes_with_one_equal_value.json
"""
import nested_diff


def test_diff():
    a = {'one': {'two': {'three': 3}}}
    b = {'one': {'two': {'three': 3}}}
    diff = {'U': {'one': {'two': {'three': 3}}}}
    opts = {}
    assert diff == nested_diff.diff(a, b, **opts)


def test_patch():
    diff = {'U': {'one': {'two': {'three': 3}}}}
    target = {'one': {'two': {'three': 3}}}
    patched = {'one': {'two': {'three': 3}}}
    assert patched == nested_diff.patch(target, diff)
