#!/usr/bin/env python3

import json
import os
import sys


def format_test(**kwargs):
    return """\
        '{name}': {{
            'a': {a},
            'b': {b},
            'diff': {diff},
            'diff_opts': {diff_opts},{patched}
        }},""".format(**kwargs)


def generate_tests(source_dir=sys.argv[1]):
    tests = []
    for file_name in sorted(os.listdir(source_dir)):
        with open(os.path.join(source_dir, file_name)) as f:
            data = json.load(f)

        test_name = file_name.replace('.json', '')

        test_opts = {}
        if 'opts' in data:
            for o in data['opts']:
                if o.startswith('no'):
                    test_opts[o.replace('no', '')] = False
                elif o == 'trimR':
                    test_opts['trimR'] = True

        if 'patched' in data:
            patched = f"\n            'patched': {repr(data['patched'])},"
        else:
            patched = ''

        tests.append(
            format_test(
                name=test_name,
                a=repr(data['a']),
                b=repr(data['b']),
                diff=repr(data['diff']),
                diff_opts=repr(test_opts),
                patched=patched,
            ),
        )

    print(
        '''"""
Do not edit manually! Generated by {script} from
https://github.com/mr-mixas/Nested-Diff/tree/master/tests/json/

"""


def get_tests():
    return {{
{tests}
    }}'''.format(
            script=sys.argv[0],
            tests='\n'.join(tests),
        ),
    )


if __name__ == '__main__':
    generate_tests()
