name: tests
on: ["push", "pull_request"]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version:
        - 3.5
        - 3.6
        - 3.7
        - 3.8
        - pypy-3.6
        - pypy-3.7
        include:
        - os: ubuntu-latest
          python-version: '3.x'

        # to catch os specific errors
        - os: macos-latest
          python-version: '3.x'
        - os: windows-latest
          python-version: '3.x'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.architecture }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --quiet --upgrade pip setuptools
        pip install --quiet --upgrade tox

    - name: Test with tox
      if: ${{ matrix.python-version != '3.8' }}
      run: |
        tox -e py

    - name: Test with tox and coveralls
      if: ${{ matrix.python-version == '3.8' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install --quiet --upgrade coveralls
        tox -e coverage
        coveralls --service=github
