name: tests
on: ["push", "pull_request"]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version:
        - 3.5
        - 3.6
        - 3.7
        - 3.8
        - pypy-3.6
        - pypy-3.7
        - pypy-3.8
        - pypy-3.9
        tox-env: ['essential']
        include:
        - os: macos-latest
          python-version: '3.x'
          tox-env: essential
        - os: windows-latest
          python-version: '3.x'
          tox-env: essential
        - os: ubuntu-latest
          python-version: '3.9'
          tox-env: linters
        - os: ubuntu-latest
          python-version: '3.x'
          tox-env: coverage
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.architecture }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --quiet --upgrade pip setuptools
        pip install --quiet --upgrade tox

    - name: Run test without coverage
      if: ${{ matrix.tox-env != 'coverage' }}
      run: |
        tox -e ${{ matrix.tox-env }}

    - name: Run tests with coverage
      if: ${{ matrix.tox-env == 'coverage' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install --quiet --upgrade coveralls
        tox -e coverage
        coveralls --service=github
